import Head from 'next/head'
import Link from 'next/link';
import { wrapper } from '../src/store';
import styles from '../styles/Home.module.css'
import PostTemplate from '../ui/templates/PostTemplate'
function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={'/posts'}> POSTS </Link>
    </div>
  )
}

export default Home;

export async function getStaticProps() {
  return {
    props: {},
  };
}
